import type { Metadata } from 'next'
import {
	Inter,
	Roboto_Condensed,
} from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
})
const robotoCondensed =
	Roboto_Condensed({
		subsets: ['latin'],
		variable: '--font-roboto-condensed',
	})

export const metadata: Metadata = {
	title: 'Create Next App',
	description:
		'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${robotoCondensed.variable}`}
		>
			<body className={inter.className}>
				{children}
			</body>
		</html>
	)
}
